
FROM ubuntu:18.04
COPY gnu-koryavov /home/gnu-koryavov

RUN apt-get update
RUN apt-get -y install sudo

RUN ["chmod", "+x", "/home/gnu-koryavov/ci-scripts/entrypoint_run.sh"]
ENTRYPOINT ["/home/gnu-koryavov/ci-scripts/entrypoint_run.sh"]
